//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int Group_ID { get; set; }
        public string Group_Name { get; set; }
        public int Students_Count { get; set; }
        public string Specialization { get; set; }
    
        public virtual Audiences Audiences { get; set; }
    }
}
