//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySort
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class University_DBEntities : DbContext
    {
        public University_DBEntities()
            : base("name=University_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Audiences> Audiences { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Semesters> Semesters { get; set; }
        public virtual DbSet<SoftwarePackages> SoftwarePackages { get; set; }
        public virtual DbSet<Softwares> Softwares { get; set; }
    }
}
