//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Softwares
    {
        public int Software_ID { get; set; }
        public string Name { get; set; }
        public int SoftwarePackage_ID { get; set; }
        public Nullable<int> SoftwarePackage_Package_ID { get; set; }
    
        public virtual SoftwarePackages SoftwarePackages { get; set; }
    }
}
