//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySort
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwarePackages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftwarePackages()
        {
            this.Softwares = new HashSet<Softwares>();
        }
    
        public int Package_ID { get; set; }
        public int Software_ID { get; set; }
        public string SoftwarePackageName { get; set; }
        public int Audience_ID { get; set; }
        public int Semester_ID { get; set; }
    
        public virtual Audiences Audiences { get; set; }
        public virtual Semesters Semesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Softwares> Softwares { get; set; }
    }
}
